### ISSUE TITLE
Ignore snyk issue `Low severity vulnerability found on braces@1.8.5` until June 30

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#113]
Ignore unresolvable synk security issue: `Low severity vulnerability found on braces@1.8.5` until June 30, 2018.

This issue is caused by babel 7 beta 42, provided by next.js and is not resolvable until a future update of next.js also updates babel.

**Comment by nnnnat** [comment]
This was done in PR #112
