### ISSUE TITLE
Add page transitions

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction-next-starterkit#125]
Integrate page transitions using this package: https://github.com/illinois/next-page-transitions

**Comment by willopez** [comment]
The current next-router, does not work well with full page transitions. Page transitions cause a full page refresh when clicking on a variant/options. This can be revisited when React Router is integrated with NextJS.

**Comment by aldeed** [comment]
Closing this since it isn't critical and won't work with non-SPA routing anyway
