### ISSUE TITLE
MiniCart Component

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#128]
# MiniCart Component
## Overview / Summary
Create a mini-cart component which requires a non-empty items array to be passed in.
This component should display a list of items, a cart summary, and any checkout buttons.
This component is necessary for displaying a mini-cart in a dropdown when an item is added to the cart or when a customer hovers over the cart icon.
This component should be added to the Storefront starter-kit

## Expected use cases
This component will be used whenever a mini version of the cart is needed, such as in the dropdown menu.

### Where should this component live
This component should be created in the starterkit.

## Images
![image](https://user-images.githubusercontent.com/1203639/40945129-94cb00fc-6814-11e8-98d5-83b4113019ab.png)

```jsx
// Pseudo-markup for the MiniCart render function
<div>
  <div scrolling-box>
    <CartItemsComponentProp/>
  </div>
  <div footer>
    <CartSummaryComponentProp/>
    <CartCheckoutButtonsComponentProp/>
    <div cart-fine-print></div>
  </div>
</div>
```

### Props
```js
propTypes: {
  cart: PropTypes.shape(),
  onRemoveItemFromCart: PropTypes.func,
  onChangeCartItemQuantity: PropTypes.func,
  Components: PropTypes.shape({
    CartItemComponent: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
    CartSummaryComponent: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
    CartCheckoutButtons: PropTypes.oneOfType([PropTypes.string, PropTypes.func])
  })
}
```

### Data Fetching
None. A HOC will later be wrapped around this component to do the GraphQL cart query and pass in the cart. For now, mock the incoming `cart` prop in `defaultProps`.

### State Store
All data comes from props. No global state used.

### Routing / Query String
The MiniCart is not directly connected to any route or query string.

### Render Criteria
- The MiniCart rendered when the customer hovers over the cart icon in the navigation header on a desktop browser. (WIRE THIS BEHAVIOR AS PART OF THIS ISSUE)
- The MiniCart is also rendered when the customer successfully adds an item to their cart. When the MiniCart is rendered in this way, the dropdown (another component) should only display for 3 seconds unless the user hovers over the cart icon or the dropdown during that timeout. (FUTURE. DO NOT WIRE THIS BEHAVIOR AS PART OF THIS ISSUE)

### Breakpoints
The MiniCart should be shown on browsers from 960px and wider

#### Normal
Zeplin: https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5ade3e09a65297b8be9388fa
The normal state of the MiniCart consists of a few sections.
A scrolling box that will contain the cart items, and a footer section that will contain the cart summary, checkout buttons and fine print.

The MiniCart cart should list items in a *max* 420px height "scrolling box". The box should only render the full height of 420px when there are 3 or more items in the cart.
If the items in the cart do not overflow, the box should be rendered to contain the items.
If the items in the cart will overflow the 420px height, a shadow should be rendered at the bottom of the box, and the box should become scrollable on the y-axis

The normal state is entered by a user having one or more items in their cart without error and while no loading or processing related to the cart is going on.

#### Empty
The MiniCart component requires at least one item in the cart to be rendered.
There are no Zeplin designs specifically for the MiniCart in an empty state.
In an empty state, the MiniCart should have the "empty cart" message and CTA from the page cart rendered within it's boundaries
Zeplin for empty cart: https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5adfb0f92f1dbdd37e7da23a

In an empty state, the cart should not render the cart items section or the footer, but instead render the empty cart message and CTA button. The CTA button should link to the home page.

The empty state is triggered by a user have zero items in their cart without error and while no loading or processing related to the cart is going on.

#### Loading / retrieving data
N/A
**Explanation:** If the cart hasn't been retrieved, we will assume 0 items, and thus the MiniCart will not be rendered at all.

#### Processing / Waiting for response
Zeplin: There are no zeplin designs for rendering the MiniCart in a processing state.
@cassytaylor suggests using this spinner overlay animation: https://drive.google.com/file/d/13xCOsXEoqDJRXaZ8FM1iIyM30BdA88Iw/view

The MiniCart may be in a processing state after customer has made a request that affects the cart, but before the server has responded. E.g. When a customer clicks "add to cart" or "remove from cart" but before the server responds, the MiniCart may be in a processing state.

While in processing state, add `isDisabled` prop to `CartCheckoutButtons`

#### Error
Zeplin: There are no zeplin designs for rendering the MiniCart in an error state.
When implementing the code for this component, handle all possible query and mutation errors and work with design to determine what to show the customer in each case.

While in error state, add `isDisabled` prop to `CartCheckoutButtons`

#### Active (e.g. button is depressed)
N/A

#### Disabled
N/A

#### Focus
N/A

### Mobile
The MiniCart is not rendered for mobile users

**Comment by cassytaylor** [comment]
Hey @spencern, this looks good to me - I just made a couple of notes:

- The height of the minicart “items” container:  420px would be the **max** height (3+ items in cart). If the cart contains one or two unique items, the height of the minicart would be the height of those items + the cart footer (see http://zpl.io/am6jwQr)
- Loading/processing states: Can we use the same “spinner overlay” animation used here during any loading/processing states? - https://drive.google.com/open?id=13xCOsXEoqDJRXaZ8FM1iIyM30BdA88Iw 
- Render criteria: The Minicart should also appear when a user adds an item to their cart from the PDP. The most recently added item should appear at the top of the cart. The timeout for the cart after adding an item should be 3 seconds (unless the user hovers over the minicart - then it would stay up indefinitely while the cursor is inside of the minicart) 
- Empty state: The solution above sounds good; can the height of the “empty” minicart be 230px?

**Comment by spencern** [comment]
@cassytaylor thanks for the clarification. I'll update the issue.

**Comment by rymorgan** [comment]
@spencern @cassytaylor this all looks great. @cassytaylor Is there are why we are limiting the height of the mini-cart to 420? I've seen other carts that go bigger on desktop and more room allows us to have a little more space in the design. For example, Nordstrom's goes up to 580px. 

<img width="186" alt="screen shot 2018-06-13 at 5 11 54 pm" src="https://user-images.githubusercontent.com/20409254/41384839-fd5c60b0-6f2c-11e8-9753-62140d97f1d6.png">
