### ISSUE TITLE
Create "Bestseller" logic for Badges

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-next-starterkit#130]
Related to #124 

We have designs to introduce a `Bestseller` badge for products, yet we have no logic to determine what constitutes a bestseller.

This is a placeholder ticket, and should be expanded upon with more details when they become clear.

**Comment by machikoyasuda** [comment]
Closing b/c it is covered here https://github.com/reactioncommerce/reaction-next-starterkit/issues/374
