### ISSUE TITLE
Create "On Sale" logic for Badges

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-next-starterkit#131]
Related to #124 

We have designs to introduce a `On Sale` badge for products, yet we have no logic to determine what constitutes an On Sale product.

This is a placeholder ticket, and should be expanded upon with more details when they become clear.

**Comment by machikoyasuda** [comment]
Closing b/c it is covered here https://github.com/reactioncommerce/reaction-next-starterkit/issues/374
