### ISSUE TITLE
Add structured data markup on the PDP

### ISSUE THREAD

**Issue by vwadher** [reactioncommerce/reaction-next-starterkit#149]
For SEO purposes its best practice to add markup / rich product information for Google and other bots to index product attributes.  More information and markup examples here - https://developers.google.com/search/docs/data-types/product 

And here are some tools to help

Use this to create structured data -  html- https://www.google.com/webmasters/markup-helper/u/0/?verticalId=4801&sourceId=103857157 

Use this to test your structured data - 
https://search.google.com/structured-data/testing-tool

**Comment by aldeed** [comment]
## Background

https://developers.google.com/search/docs/data-types/product
https://json-ld.org/

## Work

Add JSON-LD script for Google's Product schema at the bottom of the PDP page component.

**Comment by vwadher** [comment]
@aldeed For the "AggregateRating" (value and count) we would probably need to identify if the ratings and reviews plugin is installed and if so then these values should come from there.

**Comment by spencern** [comment]
@vwadher I think that it may need to be up to the plugin to add additional structured data such as rating information.

**Comment by kieckhafer** [comment]
@vwadher @spencern @aldeed 

Do we want to use `OutOfStock` of `SoldOut` for the product availability? https://schema.org/ItemAvailability

Or do we want to switch that up depending on if backorder is allowed or not?

**Comment by vwadher** [comment]
@kieckhafer @spencern @aldeed I'd say this ought to replicate & be dependent on whatever the merchant setting is on the store.  Showing the availability of a product (especially one that is demand and is in stock) can help increase the click-through rate in addition to the conversion rate.

**Comment by aldeed** [comment]
@kieckhafer The docs don't really say, but I'm guessing the assumption is that "OutOfStock" is temporary but "SoldOut" is permanent? If so, then yes I guess "Backordered" maps to "OutOfStock", else "SoldOut".

But, as @vwadher pointed out, labeling a backordered item as OutOfStock might result in the loss of a click-through because the person assumes that out of stock can't be ordered, even though they could order it. So maybe we should tag backordered ones with "InStock" even though that's not 100% true.

**Comment by vwadher** [comment]
@aldeed I'd say "backorder" should map out to = https://schema.org/PreOrder

**Comment by kieckhafer** [comment]
@vwadher @aldeed what about prices? Since this data is on the "Product" and not the "Variant" or "Option", we need to choose one of the prices to display as "the price".

I have it set right now to show the minimum / lowest variant / option price as the price. What do you think?

**Comment by vwadher** [comment]
@kieckhafer I agree with your approach.
