### ISSUE TITLE
Should tags inherit and filter products from parent tags, or have better empty states

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#151]
## Issue

With the following examples, the pure navigation tag `Some Shirt` has no products and as not been added to any product.

![some-shirt](https://user-images.githubusercontent.com/42217/41490945-2d01bf0c-70ab-11e8-8a80-53634b53c088.png)

The tag `T-Shirts` has been added to a product, and so it shows one product on its tag page.

![t-shirts](https://user-images.githubusercontent.com/42217/41490946-343fe6cc-70ab-11e8-992a-172375671d77.png)

The `Shirts` tag page shows the product `p1` since it was also added to that product.

---

## Question

Should tags act like a filter from top to bottom? Where, in this example, `Shirts` tags page has products with the `Sirts` tag, `Some Shirt` would still show all shirts as it has no additional products, and `T-Shirts` filters out all shirts and some shirts that are not t-shirts?

Or, at the very least, it could show a message urging the user back up to the "Shirts" tag where there may be products.

---

## Reproduction

- In reaction
- Add a product
- Add "Shirts" and "T-Shirts" tag to that product
- Edit the navigation tags
- Add a top-level "Shirts" tag
- Expand the dropdown
- Add a second level tag, "Some Shirts"
- Below that, add the 3rd level tag "T-Shirts"
- In the starter-kit, navigate through each level, and notice that "Shirts" and "T-Shirts" has products but "Some Shirt" does not.

**Comment by spencern** [comment]
We discussed this and this is the desired behavior. 
We can add operator functionality later that can make it easier to associate a product with all tags within a tree, but do not want to assume that behavior.
