### ISSUE TITLE
Storefront doesn't load in IE11

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#153]
When trying to access the Storefront in IE11 you'll be met with a white screen and a console error.
```sh
Expected identifier
```
Looks to be breaking at [this line](https://github.com/reactioncommerce/reaction-next-starterkit/blob/ffd0f8e9f9dfa860565d67110427f1fb215bf964/config/analytics/segment.js#L15) which made me think that we just needed to add [babel-polyfill](https://babeljs.io/docs/en/babel-polyfill.html) but it looks like we've already added it (or NextJS did).

**Comment by janus-reith** [comment]
This seems to broken again.
