### ISSUE TITLE
Connection to the graphql endpoint not working

### ISSUE THREAD

**Issue by stunjiturner** [reactioncommerce/reaction-next-starterkit#154]
http://localhost:3030/graphql-alpha is not able to load, using reaction 1.12.1 and the graphql based storefront with the reaction-api.  The error is a GET query missing. The graphiql endpoint works though?? http://localhost:3030/graphiql

**Comment by aldeed** [comment]
@stunjiturner See if it works with latest Reaction, 1.13.0. Make sure your `.env` file has everything that `.env.example` has. If it still isn't working, can you post the exact error message?

**Comment by stunjiturner** [comment]
its working well, this ecommerce framework is about to get mighty.
