### ISSUE TITLE
Manually changing the products per page limit causes dropdown to become blank

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-next-starterkit#157]
When I manually change the products per page limit in the URL (for testing purposes), the display disappears in the limit dropdown selector. The default other options are still there if I click the dropdown.

We should probably update to display whatever the limit is, even if it's not one of the defaults.

![reaction](https://user-images.githubusercontent.com/4482263/41802360-179a4564-7635-11e8-8664-32c66522139b.png)

**Comment by spencern** [comment]
We decided that a non-standard value should be ignored and the default limit should be used.
