### ISSUE TITLE
Product Grid Document Head Meta Tags

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#16]
@spencern commented on [Tue Apr 03 2018](https://github.com/reactioncommerce/reaction/issues/4124)

Add meta tags to the document head for the product grid.

The meta tags should update the meta-tag title, description, social tags (facebook og, twitter card) based on the information present in the grid such as which tag is currently being viewed.

**Comment by spencern** [comment]
@vwadher your comment about adding structured data markup fits into the general idea contained in this issue. https://developers.google.com/search/docs/data-types/product

**Comment by vwadher** [comment]
@spencern yes this is on a similar track for sure.  Ideally, we want to add all the properties of the schema.org "Product" type.
