### ISSUE TITLE
Implement Product Grid empty state designs

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-next-starterkit#160]
## Work

Add message/link to the grid component, when loading is complete but there are no items. See Zeplin design: https://zpl.io/25yYLzW

**Comment by willopez** [comment]
I have created a custom Error/Not Found page here: https://github.com/reactioncommerce/reaction-next-starterkit/pull/175 

I also added it to the grid, when no products were found. You can use that page also, for the grid. It just needs to be added to `withCatalogItems` see `withCatalogItemProduct` in my PR for reference.

**Comment by kieckhafer** [comment]
@rymorgan @aldeed What should the message / action say if we are on the Main product grid, with no filters applied, but there are no products?

This probably won't happen as that means the store is empty, but it's possible.

**Comment by rymorgan** [comment]
Can we display a different message for a store operator?

**Comment by kieckhafer** [comment]
@rymorgan we don't yet have the ability to determine user type on the starterkit, so we can't do that at this point.

**Comment by rymorgan** [comment]
Then just stick with vague messaging like - "Sorry! We couldn’t find what you’re looking for."
