### ISSUE TITLE
On a scale of 1-10 how production ready is it at this point?

### ISSUE THREAD

**Issue by EnterRavement** [reactioncommerce/reaction-next-starterkit#164]
Hey, although its stated in the description its not production ready yet, I am very interested in this project and wanted to ask, if someone who is particapting in this project to give a quick overview, how stable this version already is, what the major bugs at this point are and how long they think it will take to make this production ready. If possible I would also like to contribute

**Comment by aldeed** [comment]
@EnterRavement We hope to have a production-ready beta in a month or two. It is currently not production ready in that you can't check out yet!
