### ISSUE TITLE
PDP Media Gallery needs to toggle image set when different variants/optiion are selected.

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#165]
Currently, the PDP Media Gallery takes an array of `product.media` items and displays each image as a slide in the media gallery. 

The Media Gallery needs to be connected to which variant/option is selected and display images associated with that variant/option instead of just showing all the photos.

## Steps to reproduce
1. In RC  select the Reaction Basic Product and add images to the top level product, add a few images to the variant and do the same for each option and publish
2. View the Basic Reaction Product's PDP in the storefront. see that all the product images make it to the media gallery and the gallery doesn't change based on which option has been selected.

**Comment by aldeed** [comment]
Whoever does this, I think we should add a `media` array to the variants and options in the catalog. It would be a subset of the parent product's full `media` array, filtered by `variantId` prop. The starterkit code would simply use the `selectedVariant.media` then.

**Comment by kieckhafer** [comment]
@aldeed are you thinking this should be done somewhere inside `createCatalogProduct`: https://github.com/reactioncommerce/reaction/blob/release-1.14.0/imports/plugins/core/catalog/server/no-meteor/utils/createCatalogProduct.js#L51

Or somewhere else?

**Comment by kieckhafer** [comment]
@aldeed with your plan, what is the fallback if there is no image associated with a certain variant?

Say we have Variant A (VA), with options 1,2,3 (VAO1, VAO2, VAO3).

VA and VAO1 have an image attached to it, but VAO2 and VAO3 don't. What do we show for VAO2 and VAO3, VA's image?

What if the same scenario, but VA doesn't have an image attached, only VAO1 does. Then what do we show for VAO2 and VAO3?

**Comment by aldeed** [comment]
@kieckhafer Yes, in `createCatalogProduct`, and add a migration for existing records.

Off the top of my head, I'd say merging media all the way back up the tree makes sense. In other words:

- if I add an image to the top product itself, it should show for all variants and options
- if I add to a variant with options, it should show for every option
