### ISSUE TITLE
Product Detail Data Fetching

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#17]
@spencern commented on [Tue Apr 03 2018](https://github.com/reactioncommerce/reaction/issues/4125)

Work with the GraphQL query for `catalogProduct` defined in https://github.com/reactioncommerce/reaction/issues/4106 to create a method to fetch the data for the product detail page.

**Comment by spencern** [comment]
@jshimko once you've got a WIP branch for this will you PR it and connect it to this ticket via ZenHub?
