### ISSUE TITLE
Credit Card Payment Option component

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-next-starterkit#185]
# Credit Card Payment Option component
### Summary description of UI component
This component renders the credit card payment option. It consists of an active screen of input fields for a inputting credit card information during the checkout process, a complete screen after a card has been input, and an inactive screen, prior to input / when another option has been checked.

### Rationale for why this component is necessary
This component will allow users to add credit card information to purchase items on a shop

### Where should this component live
This component should be created in the Component Library.

### Expected use cases
This component will be used anywhere checkout is rendered

### Images / Designs of UI component in context

```jsx
// Pseudo-markup for the  render function when active
<div>
  <input name="cardNumber" />
  <input name="expiration" />
  <input name="cvv" />
  <input name="postalCode" />
  <checkbox name="saveMethod" />
</div>
```

### Props
```js
propTypes: {
  cardData: PropTypes.arrayOf(PropTypes.shape({
      _id: PropTypes.string,
      cardType: PropTypes.oneOf("amex", "discover", "mastercard", "visa"),
      cardNumber: PropTypes.string,
      cvv: PropTypes.string,
      postal: PropTypes.string,
      expiryMonth: PropTypes.string,
      expiryYear: PropTypes.string,
      isSaved: PropTypes.bool
    })),
  isSelected: PropTypes.bool,
  onClick: PropTypes.func
}
```

### Data Fetching
This component should not fetch any data.

### State Store
Local state will be used to populate the forms while fillling them out. All other data should come from props.

### Routing / Query String
Not directly connected to any route or query string.

### Render Criteria
This component should be rendered any time we are inside checkout.

### Breakpoints
This component should not specifiy it's own dimensions. It will live inside either the left column on desktop, or the full width column on mobile.

#### Normal
Zeplin:

Desktop: https://zpl.io/be4PjZl
Mobile: https://zpl.io/bPdBn16

#### Container
- All versions should be rendered inside using the `Checkout Actions` component as a wrapper.
- This component and the PayPal payment component should be developed inside a single [Selectable List](https://github.com/reactioncommerce/reaction-component-library/issues/148) component.

Desktop: https://zpl.io/be4PjZl
Mobile: https://zpl.io/bPdBn16

#### Active
The active screen will need to be fully developed. It will consist of 4 input fields: Card number, Expiration Date, CVV, and postal code. The form will need to validate. Consider using an existing Credit Card form validator, such as [React Credit Card Input](https://github.com/medipass/react-credit-card-input), to do the work for us.
<img width="576" alt="zeplin" src="https://user-images.githubusercontent.com/4482263/43117259-b5efc9b6-8ec0-11e8-8fa8-3f5c114e969e.png">

#### Inactive
This screen should be rendered before action has been taken, or when another payment type (i.e. Paypal) is selected. There are no direct designs, but you can reference the above Active state design, and just pretend the radio button is not selected.

#### Complete Screen, to be rendered once a number has been input. 
<img width="616" alt="zeplin" src="https://user-images.githubusercontent.com/4482263/43117358-45e4e1e6-8ec1-11e8-8206-11e649411580.png">

#### Saved Cards 
To be rendered if a user is logged in, and has cards saved to their accounts
<img width="616" alt="zeplin" src="https://user-images.githubusercontent.com/4482263/43117358-45e4e1e6-8ec1-11e8-8206-11e649411580.png">. When `Add New card` is clicked, `Active` state should be rendered and form should be available for user to fill in.

**Comment by aldeed** [comment]
Issue moved to [reactioncommerce/reaction-component-library #159](https://github.com/reactioncommerce/reaction-component-library/issues/159) via [**ZenHub**](https://www.zenhub.com/)
