### ISSUE TITLE
Auto deploy master to a staging URL

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction-next-starterkit#190]
This is task is to auto deploy the `master` branch of the starter kit to a staging URL, perhaps, `storefront.reactioncommerce.com`

Requirements: 

- [x] Deploy and configure an instance of reaction with sample data found here: https://github.com/reactioncommerce/reaction-catalog-sample-data

The reaction instance can be any url, as it's not meant to showcase reaction, but the storefront.

**Comment by willopez** [comment]
@spencern looping you in...

**Comment by spencern** [comment]
@willopez we'll need to make sure that there's a GraphQL API exposed somewhere as well

**Comment by willopez** [comment]
@spencern the `/graphql-alpha` path is mounted on reaction, the dev server is only for development purposes.

**Comment by griggheo** [comment]
This was done. The URL for the staging env is https://starterkit-staging.devops.reactioncommerce.com/. I'll create a PR for my changes.
