### ISSUE TITLE
Add `loading` back into withCatalogItems and pass down to components

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-next-starterkit#200]
We removed the `loading` state inside of https://github.com/reactioncommerce/reaction-next-starterkit/pull/197, as it was not being used anywhere, and was causing some issues with the way it was implemented.

This ticket should re-add that loading component, when needed, and pass the loading status down as a prop into the lower level components.

The loading logic should then be done inside whichever component is using the data, instead inside of `withCatalogItems`.

**Comment by spencern** [comment]
Work on this with #214
