### ISSUE TITLE
Mini-cart disappears with you click on any part of the popover

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#202]
## Issue

When the mini-cart is open, if you click on anything in the popover, including the white background, it will close immediately. This makes it hard to do things like trigger events for removing cart items, changing quantity, and pagination.

## Expected behavior

- Mini-cart should not close when interacting with controls from within the popover itself.
- It should close if you mouse-out, click outside the popover region, or when you navigate to a new page

## Reproduce

1. Hover over the mini cart icon
1. Hover over anywhere in mini-cart popover
1. Click, and it should disappear

**Comment by willopez** [comment]
Using a custom Popper manager as seen in the code below could be a solution. And note that Popper.js is included in MUI so there is no need to add it to the project. 

https://github.com/creativetimofficial/material-kit-react/blob/master/src/components/CustomDropdown/CustomDropdown.jsx
