### ISSUE TITLE
Wire up Cart and mini-cart summary

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#209]
Add the data fetched from the GraphQL API to the summary component for the cart and mini-cart.

**Comment by aldeed** [comment]
Seems to be a duplicate of #208

**Comment by mikemurray** [comment]
This is specifically for the cart page and mini cart drawer, not the checkout page.

**Comment by aldeed** [comment]
Or nevermind, I guess this is for non-checkout summaries. The word "checkout" in the title confused me
