### ISSUE TITLE
Flash of empty content

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#214]
When loading the list of products, I'm seeing a "Sorry, we couldn't find what you're looking for" for a brief period. This is then replaced by the list of products. It seems that until the products have been fetched, we're rendering the "couldn't find what you're looking for message. 
This appears to be what's rendered on the server as well, so it seems that perhaps the Server Side Rendering is not correctly rendering a list of products.

![image](https://user-images.githubusercontent.com/1203639/43847620-40b41424-9aee-11e8-8bbf-248af8263785.png)

**Comment by spencern** [comment]
Worth noting that this issue was seen on our test deployment and it is probably not connected to the latest 1.15.0 API, so it may not be present on the latest version.

**Comment by ltouro** [comment]
Had the same issue when using React Apollo (not SSR scenario though). Maybe it is related. See https://github.com/apollographql/react-apollo/issues/1314
