### ISSUE TITLE
Cart and PDP appear to be using different option title data

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#236]
The data used to display variant and option titles in the Cart appears to be different than what is used on the PDP.

![image](https://user-images.githubusercontent.com/1203639/44293076-2b242680-a246-11e8-8ef1-48e72dd60882.png)

**Comment by nnnnat** [comment]
Looks like the `ProductDetailOption` is using `optionTitle` from the `product.variants[x].options[x]` 
[ProductDetailOption](https://github.com/reactioncommerce/reaction-next-starterkit/blob/fddf7b03425f031de0cba3be511014cf728d7c47/src/components/ProductDetailOption/ProductDetailOption.js#L40)
and the `CartItemDetail` component is using `cart.items[x].attributes` and looping over them. [CartItemDetail](https://github.com/reactioncommerce/reaction-component-library/blob/70794031dddd9323cb87f4f7021c587c5bd292ed/package/src/components/CartItemDetail/v1/CartItemDetail.js#L125). I'm guessing the `optionTitle` is being added to that attributes array
