### ISSUE TITLE
Checkout Completed Page

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-next-starterkit#244]
# Work
Create a new page in the starter kit, for displaying a new order after checkout. (i.e., "thank you for your order" page).

## Route
`/checkout/order/:id?token=123`

## Details
- Take the ID from the route param.
- If `token` is present in the query string, use that as the order token. Else look in `anonymousOrders` local storage for that ID, to see if it's an anonymous order. If it is, use that order token.
- If we don't have a token and we aren't logged in, show a "Sign In" button with "Sign in to see your order details" above it? @cassytaylor 

## Design
Needed. Possibly just use the same design as the Meteor app for now. @cassytaylor 

Note that unlike the current Meteor app page, we will not allow adding an email on this page because we are not going to allow orders to be created without an email in the first place.

**Comment by aldeed** [comment]
@cassytaylor Are there designs in Zeplin for this page? I couldn't find it.

**Comment by cassytaylor** [comment]
@aldeed no designs, yet! I can jump on this though.

**Comment by cassytaylor** [comment]
Here is the order completed page - there may be some design tweaks (pending Ryan's review once he's back), but the information should be the same. 

http://zpl.io/agN656O

![checkout - order completed](https://user-images.githubusercontent.com/36006187/44812206-dd87b200-ab93-11e8-8d25-d05637837c9e.png)

**Comment by cassytaylor** [comment]
Updated design feat. multiple fulfillment methods is here (still pending design review, however):

http://zpl.io/bPm785l 

![multiple fulfillment methods checkout - order completed](https://user-images.githubusercontent.com/36006187/45108845-11665880-b0fb-11e8-9095-846c0b0a5f75.png)
