### ISSUE TITLE
Move login/guest component to checkout page component

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#248]
We need to investigate why `getInitialProps` method is not working in the starterkit's Pages. I think it is an implementation issue with our `_document.js` & `_app.js` components but might be an issue with nextjs.

We want to be able to use `getInitialProps` within all our Page components.
[getInitialProps](https://nextjs.org/docs/#fetching-data-and-component-lifecycle)

**Comment by spencern** [comment]
Could also potentially do this in the render function of the checkout page.

**Comment by willopez** [comment]
@nnnnat for this issue, unfortunately the `getInitialProps` approach will not work, is it only fires on the server, and we need this to be a client side navigation feature. 

I believe extracting the login + guest login forms into a component and then using it in the checkout page would be best at this point.

**Comment by nnnnat** [comment]
**Update**
Since using `getInitialProps` only fires on the server the quick fix for this is to move the Login page components into the Checkout page and handle the route/view inside the Checkout pages render method
