### ISSUE TITLE
Product Detail Metafield List

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#28]
@spencern commented on [Tue Apr 03 2018](https://github.com/reactioncommerce/reaction/issues/4136)

Create a meta-field list on the product detail page.

Should show the key and the value for a set of meta fields that are present on the product.

![image](https://user-images.githubusercontent.com/1203639/38233969-9edda11a-36d9-11e8-909d-8b7ee56e5405.png)

**Comment by spencern** [comment]
Closed because this is not a feature that we want as specified in the storefront.
