### ISSUE TITLE
Design Review Epic: PDP - Change the order of sections on mobile

### ISSUE THREAD

**Issue by rosshadden** [reactioncommerce/reaction-next-starterkit#284]
Split off from #258.

Designs: https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b0ec716a2b119e5200c72fb

The order of content on a mobile PDP page, in the mocks:

<img width="213" alt="screen shot 2018-09-24 at 5 20 17 pm" src="https://user-images.githubusercontent.com/3673236/45986081-252c1d00-c01e-11e8-948a-c96f8d3e9c9b.png">

```
[Title]
[Vendor]
[Price]

[Photo gallery]
[Variants, as dropdowns]
[Quantity input]
[Add to cart]

[Description]
```

<img width="340" alt="screen shot 2018-09-24 at 5 18 23 pm" src="https://user-images.githubusercontent.com/3673236/45986066-0c236c00-c01e-11e8-9204-c09ed86a0e29.png">
<img width="337" alt="screen shot 2018-09-24 at 5 18 27 pm" src="https://user-images.githubusercontent.com/3673236/45986067-0c236c00-c01e-11e8-8bff-d809c11c0bc5.png">

The order of content on a mobile PDP page, in current master:

```
[Title]
[Photo gallery]
[Price]
[Description]
[Variants]
[Quantity Input]
[Add to cart]
```

**Comment by aldeed** [comment]
@cassytaylor or @machikoyasuda Can you add more specific details about the reordering necessary, and links to the relevant Zeplin designs?
