### ISSUE TITLE
Error state designs for checkout page

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction-next-starterkit#340]
### Summary
What should be displayed if the credit card processor (Stripe, etc) encounters an error when processing a payment? See checkout page for context.

![screen shot 2018-09-26 at 2 30 27 pm](https://user-images.githubusercontent.com/486340/46110544-ce971e00-c198-11e8-9143-b6751429c670.png)

Here is an example of a CC processing error.
![cc_error](https://user-images.githubusercontent.com/486340/46110573-ea022900-c198-11e8-9c37-7662c32f4abe.png)

### Stripe API

Test for these errors
https://stripe.com/docs/testing#cards-responses

**Comment by willopez** [comment]
@reactioncommerce/design

**Comment by cassytaylor** [comment]
Hey @willopez, the documentation for Inline Alerts is now available here - http://zpl.io/bPm5XKl

Just to clarify, in the instance of a payment error, we should show the Error inline alert in addition to the field-level validation errors (such as "Incorrect card number" below the credit card number field, etc.)
