### ISSUE TITLE
Plan/Document handling static assets in storefront

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#354]
# Static Assets Documentation 
### Summary description
Currently, we've got several "static" assets being used by the storefront all being handled in slightly different ways.

  *  Source Sans Pro font being served by fonts.google.com / not configurable.
  *  Favicons being served from assets.reactioincommerce.com / configurable URL via .env
  *  Product Placeholder GIF being served locally from `./src/static/` / configurable URL via .env
  *  Shop locales are being served locally from `./src/lib/utils/locales.json` / not configurable. 

**Questions**
  1. Should all assets come from the same place? (`./src/static/...`)
  2. Should all assets have configurable URLs?
  3. Should we have docs/examples of using assets w/ CDN?

### Rationale for why this feature is necessary
At the very least document the why/how around the use of these assets or create an epic around a better implementation.

**Comment by nnnnat** [comment]
To clarify question 2, I mean should the assets path come from the `.env`? 
I see a possible implementation being everything lives in `src/static` by default but the path could be replaced via `.env` variable. 
```js
const assetsPath = env.process.ASSETS_PATH || "./src/static/";
```

**Comment by aldeed** [comment]
From NextJS docs: https://github.com/zeit/next.js/#static-file-serving-eg-images

> Note: Don't name the static directory anything else. The name is required and is the only directory that Next.js uses for serving static assets.

So, yes let's move all to `static` but skip the ENV var for now. We can add that if we find that many people are changing it.

I believe this will properly include static assets in the production build then?

For "Source Sans Pro", I think we should continue to load that from Google to benefit from CDN caching. We may want to document how/where to remove/change it if someone changes to a different default font.
