### ISSUE TITLE
Determine if react-helmet can be removed, and remove it

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction-next-starterkit#356]
# Remove react-helmet

### Summary description
After updating to NextJS 7, this warning is being issued on the console: 
```
 Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
```

It seems that `react-helmet` is not necessary when using NextJS, see: https://github.com/zeit/next.js/issues/5240#issuecomment-423480835

It we can easily remove it, then, lets do it and it will remove the waring above and simplify the codebase.

**Comment by spencern** [comment]
@willopez what will need to be done to remove `react-helmet`?
What work can be done to determine the answer to your question of how easy it is? Can you just remove it and see what's broken?

**Comment by willopez** [comment]
I was able easily remove the console waring, helmet is still being used, which is OK.

**Comment by spencern** [comment]
@willopez should/can we close this issue if we're going to commit to using `helmet` for the foreseeable future?

**Comment by willopez** [comment]
@spencern yes, closing.
