### ISSUE TITLE
Implement address validation.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction-next-starterkit#366]
# Feature Name
Address validation

### Summary description
There should be a UI for address validation where the address returned by the tax/shipping API could be displayed to the user and then s/he can choose the suggested address or continue with the current address.

### Rationale for why this feature is necessary
All the tax calculation and shipping service expect the address to go through their validation APIs before processing the order/request.

### Expected use cases
1. Address validated – the submitted address was correct and / or standardized
2. Address was standardized and is deliverable. Can be updated without informing customer
3. Address was corrected, there are suggested addresses(array of suggested addresses)
4. Address was checked but could not be corrected, suggested addresses have a higher probability of delivery
5. Address could not be validated, address validation service does not support the address country, etc.
6. Unable to contact provider.

The backend for address validation code should be written keeping in mind that other plugin might just want to call their own function for address validation. This would also set up the API which the plugins can follow and the format the plugins have to follow.

**Comment by zenweasel** [comment]
@aldeed Are there any details on that or can we assume it will meet the use cases specified above?

**Comment by aldeed** [comment]
@zenweasel The plan is to implement the same as how it works in the Meteor UI, but with an updated design. Zeplin design is here: https://zpl.io/VxkMEXX

It's not clear to me whether the "Expected use cases" in this issue description are something that needs to be tagged on the address itself. We don't have plans to do that.

The UI will validate every address by default before saving, but the server will not. It will save whatever you give it, assuming that you have previously validated it if you want to.

**Comment by zenweasel** [comment]
Different address validators act differently. The existing use case is for Shippo/Avalara where we get back a "corrected" address but other validators such as Radial give us back a list of "possible matches". So I think the "plugin" probably needs to somehow be able to implement it's own UI somehow rather than a "one size fits all" approach that we have now

**Comment by aldeed** [comment]
@cassytaylor Do you have any designs for a "possible matches" address review component? I guess similar to the current design, but with more than one "fixed" address shown. Could we adjust the design to be vertical so that it would work for both types of address validation (single corrected vs. multiple matches)?

**Comment by cassytaylor** [comment]
@aldeed that's not something we have designs for currently - but I can work on a mock for that.

**Comment by nnnnat** [comment]
**Update:**

We've got most of the UI built and should be merged soon after some clean-up/docs work.
[AddressReview](https://github.com/reactioncommerce/reaction-component-library/pull/336)

Once we've got that component merged we'll be working on adding it to the checkout flow and then into the starterkit once we've got endpoints.
[ShippingAddressCheckoutAction update](https://github.com/reactioncommerce/reaction-component-library/issues/338)
