### ISSUE TITLE
Respect server settings for which payment methods to show

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-next-starterkit#370]
## Work
During checkout, query `availablePaymentMethods` from the server and show UI based on the response. Currently we only have a component to show when the `name` is `stripe_card`. If none of the available payment methods have the name `stripe_card`, show an error message where that checkout step should be. In the Meteor UI it shows:

```html
<div class="alert alert-danger">
        <span data-i18n="checkoutPayment.noPaymentMethods">No payment methods are configured.</span>
        <span data-i18n="checkoutPayment.contactAdmin">Please contact the store administrator.</span>
</div>
```

Do something similar to that.

**Comment by zenweasel** [comment]
I think this is related to ongoing work to remove the "hard-coded" nature of the current Stripe plugin.

@rosshadden Are you still working on this?

**Comment by aldeed** [comment]
Ross is not, so I removed him. Hopefully we can get to this while cleaning up the checkout actions flow soon

**Comment by aldeed** [comment]
I have multiple payment methods working in starterkit now, but I opted not to respect the server settings. This is an extra query and wouldn't actually work unless you've wired up the associated checkout components for the payment method anyway. We could do this query and hide any methods that are disabled in the future if we want, but it seems like an edge case. If there does happen to be a payment method set up in starterkit which is then disabled on the server, you get a message telling you this when you click "Place order", which is good enough for me.
