### ISSUE TITLE
PDP: Badge is not shown/respected on PDP

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-next-starterkit#374]
Type: **major**

**Describe the bug**
When quantity is set to 0 and allow backorder is turned off the option that is sold out should show a "Sold Out" badge and block adding to cart.

Here is how it is reflected in the "classic UI"
![2018-10-09_16-35-52](https://user-images.githubusercontent.com/72819/46656776-69541b80-cbe1-11e8-99a4-ead547d6855e.png)

In the storefront UI, same product
![2018-10-09_16-36-44](https://user-images.githubusercontent.com/72819/46656839-8852ad80-cbe1-11e8-8678-285dcbcf5a44.png)

**To Reproduce**
1. Go to any product as an admin
1. Set the quantity for a variant to 0
1. Ensure the "Allow Backorders" flag is turned off
1. Publish
1. Observe that the badge is not shown

**Expected behavior**
The badge should be shown

**Version:** (from package.json) 1.0.0

**Comment by mikemurray** [comment]
@spencern @reactioncommerce/design I don't see a design in zeplin for how to display badges for the text-based variants and variant options. I see designs for variants that are image boxes, but that won't exactly work in this situation as it could cover text.

### Questions

- Will we be using the same style as Reaction, having them offset out of the container?
- What badges are to be displayed? We have `sold out`, `low inventory`, `sale`, etc and some of them are on the right for the grid.

![timberlands___reaction](https://user-images.githubusercontent.com/42217/46690082-50824080-cbb6-11e8-9cd3-197d5e23e534.png)

**Comment by rymorgan** [comment]
@cassytaylor Do we have badge designs for this?

**Comment by cassytaylor** [comment]
@rymorgan  @mikemurray (cc @zenweasel )-
 Badging designs for the PDP can be found here: http://https://zpl.io/bzMBLpz

I'm still working on Sale badging for the variant level (text-based) and variant option level. Those mocks should be available today!

Per the original bug, **we do have designs for Sold Out variants and variant options (and other inventory messaging):**

When a variant and all of its options is sold out, the variant (both text- and image-based) should be set to 20% opacity. The variant can still be selected; all of its options should be set to 20% opacity and an "Out of stock" message should display below them. 
![pdp - badging- oos color variant selected](https://user-images.githubusercontent.com/36006187/46758078-1f267500-cc89-11e8-99cd-61d2ef66159e.png)
http://zpl.io/be45KKq


This mock shows a Sold Out variant option selected. It filters the other variants by the selected options, too - ie the grey shorts are the only ones available in XL. (Not sure if this is in scope)
![pdp - badging- oos size variant selected](https://user-images.githubusercontent.com/36006187/46758261-ad9af680-cc89-11e8-82c3-59fec5dadf0c.png)
http://zpl.io/agnDkk1

We also have **Low inventory messaging**, shown  at the variant option level (it would be shown at the variant level, if there are no variant options): http://zpl.io/brrnMMX

**Backordered messaging** at the variant option level (would show at the variant level if applicable, same as above): http://zpl.io/bAvdl8B

The **Bestseller** badge appears on the main product image: http://zpl.io/aMm8ppK

**Mobile mocks**: http://zpl.io/25y0pp3, http://zpl.io/bzMB6JA, http://zpl.io/2j8oY4x

**Comment by cassytaylor** [comment]
Mocks for "Sale" badging on text-based variants:
http://zpl.io/a8NO6wQ
http://zpl.io/aMvMQP3

**Comment by zenweasel** [comment]
@mikemurray The `backorder` badge is also not showing. Do we need to open a separate issue or will this get fixed with this when `sold out` is fixed?

**Comment by spencern** [comment]
@mikemurray @nnnnat any idea as to the answer of @zenweasel's question here?

**Comment by nnnnat** [comment]
Sorry @spencern this has been discussed in meetings but the ticket hasn't been updated. In short, this ticket has become a catch-all for implementing product badges on the storefront PDP. 

@mikemurray has a correction to catalog badges currently in review/progress that should address how `sold out`, `low inventory` and `backorder` badges are determined and provided, after that's merged we can knock this ticket out. Currently, as Reaction publishes products to the Catalog it incorrectly sets `isSoldOut` and `isLowInventory` to `false` on all variants and options. This is why a customer can still buy a sold out item and no badges will ever display on the PDP in the storefront.

We've also talked to @reactioncommerce/design about implementing more of the PDP UI from zeplin that @machikoyasuda or I still need to scope out in component-library tickets, but that shouldn't block getting this resolved since we can roll out the updated UI as it gets built.

**Comment by kieckhafer** [comment]
This kind of became a catchall for all badge related issues in the starterkit.

I've fixed all the Inventory related issues, and updated the designs for all Inventory related badges / text / etc. This is all done in PR #459

I'm leaving this ticket open as a reference for all Sale / Best Seller work that needs to be done.

**Comment by spencern** [comment]
Thanks @kieckhafer - we could consider a separate ticket for that, but not urgent to create it and move details over.
