### ISSUE TITLE
The prop `primaryShopId` is marked as required in `WithTag`, but its value is `undefined`.

### ISSUE THREAD

**Issue by Able2Code** [reactioncommerce/reaction-next-starterkit#381]
Type: **minor**

**Describe the bug**
after installing a fresh version ( no old images on docker ) I get this error by visiting localhost: 4000
reaction container fails to start

**To Reproduce**
1. install reaction platform
2. make
3. make start
4. visit localhost:4000

**Expected behavior**

**Screenshots**
<img width="978" alt="schermata 2018-10-10 alle 19 13 51" src="https://user-images.githubusercontent.com/5517831/46754189-23bb4f80-ccc2-11e8-9972-0e0caef22b6b.png">

reaction output :

 { Error: Command failed: meteor --raw-logs
     at checkExecSyncError (child_process.js:601:13)
     at execSync (child_process.js:641:13)
     at _callee$ (/usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:72:43)
     at tryCatch (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:65:40)
     at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:303:22)
     at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:117:21)
     at step (/usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:98:191)
     at /usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:98:361
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:188:7)
   error: null,
   cmd: 'meteor --raw-logs',
   file: '/bin/sh',
   args: [ '/bin/sh', '-c', 'meteor --raw-logs' ],
   options:
    { stdio: [ [Object], [Object], [Object] ],
      shell: true,
      file: '/bin/sh',
      args: [ '/bin/sh', '-c', 'meteor --raw-logs' ],
      envPairs:
       [ 'TOOL_NODE_FLAGS=',
         'NODE_VERSION=8.11.3',
         'HOSTNAME=505019d82c3b',
         'METEOR_VERSION=1.7.0.3',
         'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor',
         'PWD=/opt/reaction/src',
         'MONGO_URL=mongodb://mongo:27017/reaction',
         'APP_BUNDLE_DIR=/opt/reaction/dist',
         'ROOT_URL=http://localhost:3000',
         'SHLVL=1',
         'HOME=/home/node',
         'YARN_VERSION=1.6.0',
         'REACTION_DOCKER_BUILD=true',
         'APP_SOURCE_DIR=/opt/reaction/src',
         'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
         'HYDRA_ADMIN_URL=http://hydra:4445',
         'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
         '_=/usr/local/bin/reaction' ],
      killSignal: undefined },
   envPairs:
    [ 'TOOL_NODE_FLAGS=',
      'NODE_VERSION=8.11.3',
      'HOSTNAME=505019d82c3b',
      'METEOR_VERSION=1.7.0.3',
      'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor',
      'PWD=/opt/reaction/src',
      'MONGO_URL=mongodb://mongo:27017/reaction',
      'APP_BUNDLE_DIR=/opt/reaction/dist',
      'ROOT_URL=http://localhost:3000',
      'SHLVL=1',
      'HOME=/home/node',
      'YARN_VERSION=1.6.0',
      'REACTION_DOCKER_BUILD=true',
      'APP_SOURCE_DIR=/opt/reaction/src',
      'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
      'HYDRA_ADMIN_URL=http://hydra:4445',
      'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
      '_=/usr/local/bin/reaction' ],
   stderr: null,
   stdout: null,
   pid: 73,
   output: [ null, null, null ],
   signal: null,
   status: 137 }

 Error: App failed to start
reaction_reaction_1 exited with code 1

**Desktop (please complete the following information):**
 - OS: Mac Os High Sierra 10.13.6
- Docker : Version 18.06.1-ce-mac73 (26764)

**Comment by aldeed** [comment]
@Able2Code The `primaryShopId` error is just because it can't access the API service. As for why that didn't start up, it could be any one of a number of known issues with fixes coming soon. Some would be fixed by just stopping and starting again. It could also be that you need to increase resources allocated to Docker. Refer to https://docs.reactioncommerce.com/docs/troubleshooting-development#docker-issues

**Comment by Able2Code** [comment]
@aldeed , true, by adding more memory to docker all works well, thank you !
