### ISSUE TITLE
(TypeError): Cannot read property 'original' of null

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#387]
Type: **minor**

**Describe the bug**
A TypeError is thrown when a product without images is added to the Cart.

**To Reproduce**
1. In RC create a product without images
2. In the starterkit select that product and try to add it to the Cart.
3. See TypeError

**Expected behavior**
[getCartItemTrackingData](https://github.com/reactioncommerce/reaction-next-starterkit/blob/03b50ab1ef021235536115ceb119ebebbae0dd0e/src/lib/tracking/utils/getCartItemTrackingData.js#L36) needs to check `variant.imageURLs` before using `variant.imageURLs.original`

**Comment by willopez** [comment]
Resolved in #388
