### ISSUE TITLE
UI support for multiple payment methods

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction-next-starterkit#404]
### Feature Name
UI support for multiple payment methods

### Summary description
We need the `CheckoutActions` component to display possibly more than one payment method (ex. credit card + Paypal). A user should be able to choose 1 payment method from a list of multiple methods. (This ticket is not for a user using 2 different methods for 1 order).

One option is to have one `CheckoutAction` component per payment method and another option is to stick with only one `CheckoutAction` component to handle multiple payment methods.

- PayPal

**Comment by zenweasel** [comment]
@ajporlante Was this issue worked around of do we still need to design and create a new component here?

**Comment by zenweasel** [comment]
Something very similar is going to come up with Loyalty Rewards as they will be created as a payment type, but they need to be able to combine them with another payment type

**Comment by zenweasel** [comment]
@ajporlante Second call on this question

> Was this issue worked around or do we still need to design and create a new component here?

**Comment by aldeed** [comment]
Done
