### ISSUE TITLE
SSR not working properly for the Product Grid and PDP pages

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#405]
Type: **critical**

**Describe the bug**

The product grid being is not being fully rendered on the server with SSR before sending to the browser. It's only rendering 1 or 2 items initially. React in the browser then replaces with the full listing of products for that page.

The PDP page gets the navigation header rendered initially with the body of the page being blank. React then later renders the body of the page with the correct product info.

**To Reproduce**

1. Navigate to http://localhost:4000 from the address bar to trigger a full page load
2. See a short list of blurry products loaded initially
3. After a second, the full set of products for that page will be rendered

---

1. Navigate to a PDP page
2. Notice that the page is blank for a second...
3. Then the content for the PDP page is rendered

---

1. Disable JS
2. Navigate to the homepage
3. See that the entire page of products does not load
4. Navigate to a PDP page
5. See that the body of the page is not rendered

**Expected behavior**

Pages rendered with SSR should be representative of the data they should be displaying. If there are 20 products on the grid, then all 20 should be rendered with SSR.

**Screenshots**

Grid:
<img width="1148" alt="reaction" src="https://user-images.githubusercontent.com/42217/47465327-59236b00-d7a1-11e8-9cae-0f25091329a6.png">

PDP:
<img width="1156" alt="timberlands___reaction" src="https://user-images.githubusercontent.com/42217/47465387-9851bc00-d7a1-11e8-898c-628a434a4e8b.png">

**Desktop:**
 - OS: MacOS Mojave
 - Browser Chrome
 - Version 69.0.3497.100

**Comment by spencern** [comment]
@mikemurray - good find. This appears to be a recent regression as I've been testing with js disabled a few times over the last month and this is the first time I've seen this issue. 

You can also see this issue on our staging environment.
