### ISSUE TITLE
Google Search Console Account Validation

### ISSUE THREAD

**Issue by vwadher** [reactioncommerce/reaction-next-starterkit#411]
# Feature Name
Google Search Console Integration

### Summary description
Use the google search console account url code from this issue and leverage the graphQL API to publish the value in a manner to allow google bots to validate the ownership of the storefront URL.

https://github.com/reactioncommerce/reaction/issues/4784  

### Rationale for why this feature is necessary
To update the existing google search console plugin in order to allow google to crawl and index Reaction storefront sitemaps and leverage all other webmaster tools within Google Search Console. 

### Expected use cases
- Enter the front end store URL in google search console 
- Enter the google search console url code in the back end operator app
- In google search console verify the storefront url is associated with the google search console account.

**Comment by zenweasel** [comment]
Closing as not necessary
