### ISSUE TITLE
Shipping address full name is not autofilled when form is reloaded

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction-next-starterkit#414]
Type: **minor**

**Describe the bug**
Shipping address full name is not autofilled when form is reloaded, that is when user has already filled in the form and saved it, then clicks "Change.". The full name doesn't appear after `Save` is clicked either.

**To Reproduce**
1. Create a cart and checkout.
2. Fill in the shipping address form, then click "Save."
3. Click "Change" in the shipping address section.
4. See that full name is not filled.

<img width="1440" alt="screen shot 2018-11-05 at 1 14 43 pm" src="https://user-images.githubusercontent.com/3673236/48027170-e26d6280-e0fc-11e8-9b6f-d14011f61ce1.png">
<img width="1440" alt="screen shot 2018-11-05 at 1 14 46 pm" src="https://user-images.githubusercontent.com/3673236/48027172-e305f900-e0fc-11e8-8d53-1117329b86e4.png">

**Expected behavior**
Full name should be autofilled like the other shipping info.

**Comment by machikoyasuda** [comment]
@nnnnat Is this bug related to the fact that Component Library/the Address Form field takes `fullName` but GraphQL/Starter Kit save them separately as `firstName`, `lastName`?
