### ISSUE TITLE
Implement Google sitemap functionality

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-next-starterkit#422]
# Feature Name
Implement Google sitemap functionality

### Summary description
Need to provide a sitemap.xml in Google's format with child maps similar to what was implemented [here](https://github.com/reactioncommerce/reaction/pull/4413) in the Meteor app.

### Rationale for why this feature is necessary
This is required by Google to crawl all of your pages

### Expected use cases
Most ecommerce site would need this for proper SEO

**Comment by zenweasel** [comment]
@impactmass @dancastellon  Wasn't this completed?

**Comment by impactmass** [comment]
yes, I completed this using this https://github.com/reactioncommerce/reaction/issues/4796. I did not see this issue back then.

PRs: 
https://github.com/reactioncommerce/reaction/pull/4927, reactioncommerce/reaction-next-starterkit#488, and https://github.com/reactioncommerce/reaction-next-starterkit/pull/497
