### ISSUE TITLE
Add tax description to PDP

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-next-starterkit#431]
Variants have a `taxDescription` property that operators can edit, but this doesn't show anywhere on the PDP. Add it. Needs design input.

**Comment by zenweasel** [comment]
I always thought this value was just for tax reporting, not for displaying to consumers

**Comment by aldeed** [comment]
If so, we'd need to document it as such. But what then would an example be? Not sure I get it.

Often you see a blurb on store PDPs like "5% sales tax will be added if shipped to NY", which is what I thought this was for. But even that seems like something that could be better handled a different way.

We could also just remove this field from UI and schema if nobody knows what it's for.

**Comment by zenweasel** [comment]
You need a description that applies to what sort of product it is which is relevant to tax reporting. 
 In CA this is a quarterly report where you list every single thing you sold and what you need to pay for it. Marketing descriptions don't always make any sense in the context of their taxable type. Often there will be a bunch of stuff labeled something like "General Merchandise" but then for non-taxable you need something that makes it clear why it's non-taxable e.g. "Promotional Items". I know for a fact this is how Avalara uses that field. AFAIK it's very much required.

**Comment by aldeed** [comment]
Oh so this would be expected to be sync'd over to the third-party tax service? I think that's the missing piece I wasn't understanding. Because I assume that anyone using a third-party tax service would log in to the tax service dashboard to generate their tax reporting forms.

Regardless, there's no documentation about what you're supposed to enter here, so that should be fixed. But that maybe is better tracked as an issue in the reaction repo.

**Comment by zenweasel** [comment]
RIght, they would log into the service, but the reporting would display the "Tax Description" rather than some crazy long, and possibly not helpful, marketing message.

afaik there is no reason for it to ever show up on the consumer side.

**Comment by aldeed** [comment]
Closing in favor of https://github.com/reactioncommerce/reaction/issues/4877
