### ISSUE TITLE
Server crashes when user navigates to localhost:4000 (homepage)

### ISSUE THREAD

**Issue by srikanthkolli** [reactioncommerce/reaction-next-starterkit#433]
Type: **critical**

**Describe the bug**
Node Server crashes because of logger **debug** is not defined. I'm using reaction-platform to setup the microservices.

**To Reproduce**
After starter kit docker container is started navigating to localhost:4000 shows continues loading screen

**Expected behavior**
Should show the home screen when user navigates to localhost:4000

**Screenshots**
![error_screen](https://user-images.githubusercontent.com/4520674/48932398-b6861580-ef21-11e8-9682-ccdf0847f191.jpg)

**Comment by machikoyasuda** [comment]
Hi @srikanthkolli - Thanks for the ticket. We fixed this in this PR: https://github.com/reactioncommerce/reaction-next-starterkit/pull/428

Can you try the latest `develop` branch to see if you still get this bug?
