### ISSUE TITLE
Address Validation Zip comparison is incorrect

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction-next-starterkit#436]
Type: **minor**

**Describe the bug**
The UI that compares the entered address and the suggested address is not showing the comparison correctly when the zip is different in the suggested address.

**To Reproduce**
1. Modify the test-address-validation to return 
```js
{ suggestedAddresses:
   [ { address1: '1075 First Ave',
       city: 'King of Prussia',
       region: 'PA',
       country: 'US',
       postal: '19406-1418' } ],
  validationErrors:
   [ { summary: 'AddressLine1', type: 'AddressLine1' },
     { summary: 'City', type: 'City' } ] }
```
2. Activate address validation via Admin
3. Enter the "enterred address" address as shown in the screenshot below.
4. After clicking "Save changes" you will be taken to the address comparison screen which shows the error. Observe how the zip is displayed on two separate lines.

**Expected behavior**
Correct address should be displayed in the "Suggested Address" area.

**Screenshots**
<img width="487" alt="screenshot 2018-11-27 at 10 53 17 pm" src="https://user-images.githubusercontent.com/7762605/49099748-369cda00-f298-11e8-8f91-839d32d1de15.png">

**Comment by nnnnat** [comment]
Issue moved to [reactioncommerce/reaction-component-library #373](https://github.com/reactioncommerce/reaction-component-library/issues/373) via [**ZenHub**](https://www.zenhub.com/)
