### ISSUE TITLE
Tags/NavBuilder: Navigation should come from new Nav object

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-next-starterkit#446]
As a Reaction storefront user, I can view the navigation built by the admin, so that I can see a nice custom Navigation.

As a followup to https://github.com/reactioncommerce/reaction/pull/4683, the navigation should come from the new navigation tree object.

## Dependency
https://github.com/reactioncommerce/reaction/pull/4683

**Comment by zenweasel** [comment]
@machikoyasuda We were looking at asking @kieckhafer to do this as part of the SE team since this is something we need but are y'all going to handle it?

**Comment by machikoyasuda** [comment]
@zenweasel We are _not_ going to be doing it in this Sprint. @kieckhafer - it's all yours.

**Comment by dancastellon** [comment]
More info from the ticket I had created: https://github.com/reactioncommerce/reaction-next-starterkit/issues/427

**Comment by kieckhafer** [comment]
@zenweasel @dancastellon is there a limit to how deep the tag tree can go? Currently I think we have two levels of sub tags under navigation. Are we keeping it at two levels? and if not, do we have designs for going deeper than 2?

**Comment by dancastellon** [comment]
@kieckhafer I believe we agreed to keep it as is - 3 levels deep (Shoes -> Casual -> Sneakers for example).

**Comment by zenweasel** [comment]
Yeah, I think we currently support 3 (at least in the Classic UI we did) and that's all we should do for now

**Comment by kieckhafer** [comment]
This issue is complete in PR #472, no additional work needs to be done. However, since we currently have no UI for editing Navigation, we are waiting to merge #472 until the Nav UI is completed https://github.com/reactioncommerce/reaction/issues/4810
