### ISSUE TITLE
Update and fix integration test to work on CI

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-next-starterkit#456]
Type: **minor**

**Describe the bug**
Integration tests fail on CI. They rely on `localhost:4000`, but we don't have any step that starts the NextJS server first.

**To Reproduce**
Remove `.skip` from the test in `/tests/integration` and push a PR. Integration test step will fail on CircleCI.

**Expected behavior**
Integration tests work on CI.

**Additional context**
More details from @jeffcorpuz:

> Originally it was pointing to the staging starter kit environment while I was trying to sort out how to make it work there.
> 
> It seems along the way it changed to `localhost` for people to test it locally.
> 
> I was planning on migrating this test out to Jest as well to remove `mocha` + `superagent` dependencies.
> 
> How it was intended to work was CI run the application via container, expose the port 3000/4000  and run the e2e and integration test on that.
> 
> However anytime I have tried actually running the application it would just time out. Been a blocker for me in actually getting everything connected for automation.
> 
> The environments have been a nice workaround but it isn’t stable.

**Comment by spencern** [comment]
Has this issue been resolved now?

**Comment by jeffcorpuz** [comment]
@spencern should be resolved with above PR ^
https://github.com/reactioncommerce/reaction-next-starterkit/pull/473

tagged @aldeed & @griggheo
