### ISSUE TITLE
Items subtotal is incorrect when same option is added to cart

### ISSUE THREAD

**Issue by ajporlante** [reactioncommerce/reaction-next-starterkit#462]
Type: **major**

**Describe the bug**
Clicking add to cart twice miscalculates the items subtotal. Please see image below:
<img width="381" alt="screen shot 2018-12-15 at 2 03 13 am" src="https://user-images.githubusercontent.com/10388757/50022126-ae476480-000d-11e9-8b58-9a428d2f4f77.png">

**To Reproduce**
1. Go to a product page.
2. Click Add To Cart twice.
3. See that items subtotal is incorrect as displayed in the mini-cart.

**Expected behavior**
In the above image, subtotal should be 39.98

**Comment by kieckhafer** [comment]
PR ready: reactioncommerce/reaction#5021

**Comment by kieckhafer** [comment]
Fixed in https://github.com/reactioncommerce/reaction/pull/5021
