### ISSUE TITLE
Start failed

### ISSUE THREAD

**Issue by kodermax** [reactioncommerce/reaction-next-starterkit#475]
![image](https://user-images.githubusercontent.com/590985/50897660-d912b600-141d-11e9-9aa9-a6b2c7269ffd.png)

**Comment by aldeed** [comment]
Please verify that you have latest `develop` branch checked out for all the platform repos, and pull latest. This was an issue for awhile but should be fixed in `develop` and will be fixed in RC8 to be released soon.
