### ISSUE TITLE
Rename this project/repo

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#476]
Type: **breaking|critical|major**

**Describe the bug**
The `reaction-next-starterkit` name came about mostly as an inside joke that made it all the way to the repo. The name is extremely confusing to not only the community but within the Reaction team. 

**To Reproduce**
1. Go to the `reaction-next-starterkit` repo.
2. Read the project name.
3. You should now be confused.

**Expected behavior**
A clear project/repo name that accurately conveys the reference/example intent of this project.

**Additional context**
I see two deliverables here before we actually change the projects name.
1. [x] Pick a new name: Current front runner `example-storefront`
2. [ ] Audit other Reaction repos that may reference this project by name. (i.e., `reaction-platform`)

**Comment by zenweasel** [comment]
I think having the technology name in the title is helpful in case we have a "vue-Storefront" or something

**Comment by spencern** [comment]
@zenweasel this project may not be our only example ultimately as well.

**Comment by zenweasel** [comment]
@spencern Yeah, that's what I meant

**Comment by zenweasel** [comment]
@focusaurus There was previously talk about calling this whole thing (the entire no-Meteor/GraphQL initiative) "Next" as opposed to 2.0 so I think the idea was it meant both "the next thing" **and** NextJS. Because haha clever.

More importantly I think we also need to do some more deep thinking about what purpose this project serves. Is it really just a "reference" or do we want/expect that people will just build on top of it. I think this gets to the core of "what exactly is the product?" That discussion is ongoing

**Comment by spencern** [comment]
@focusaurus good points. A goal for our `example` storefront is that it can serve as a functionally complete implementation. It's one example of how to consume our commerce GraphQL API.

I'll retract the suggestion that we use the term `reference` and back the use of `example`.

Additionally, I agree that it's very important to be clear when we're referencing technology (e.g. `nextjs` vs `next`) 

Which technologies are important to include in the name/slug?
E.g. is this the `example-nextjs-react-apollo-storefront` (or `example-storefront-nextjs-react-apollo`) or is `example-nextjs-storefront` enough?

**Comment by chrispotter** [comment]
to throw in my 2¢ it might be better to name repos `example-storefront-<techname>` for sorting/searching purposes within the reaction org.

Might it also be beneficial to separate these into a `reaction-storefront` grouping (like how we have `reaction-contrib-org`) where we can just have `example-nextjs` etc? 

This might naturally alleviate the association between our versioned/supported headless API and the storefront jumping off examples.

**Comment by willopez** [comment]
@nnnnat Have we settled on a new name?
