### ISSUE TITLE
Package.json still uses GPL-3.0 license

### ISSUE THREAD

**Issue by mihaur** [reactioncommerce/reaction-next-starterkit#509]
Type: **major**

**Describe the bug**
With https://github.com/reactioncommerce/reaction-next-starterkit/pull/339 the project license was set to Apache 2.0. package.json still references old GPL 3 ("license": "GPL-3.0") instead of "Apache-2.0"

**Comment by machikoyasuda** [comment]
Thank you for noticing this and bringing it up.
