### ISSUE TITLE
Add a demo

### ISSUE THREAD

**Issue by romainquellec** [reactioncommerce/reaction-next-starterkit#516]
# Feature Name
Add a demo

### Summary description
Well, title say it all.

### Rationale for why this feature is necessary
Try the front to see what to expect.

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #58](https://github.com/reactioncommerce/reaction-feature-requests/issues/58) via [**ZenHub**](https://www.zenhub.com/)
