### ISSUE TITLE
Envalid returns  Missing environment variables even after creating a .env file

### ISSUE THREAD

**Issue by ianlikono** [reactioncommerce/reaction-next-starterkit#526]
Type: **breaking**

**Describe the bug**
I tried running on my local machine without docker, but I am getting an error of missing environmental variables and i already have the .env file in the root of my project. I dont know what is making it to do that.

![Screen Shot 2019-04-22 at 9 59 45 AM](https://user-images.githubusercontent.com/15727947/56506914-72556c00-64e5-11e9-9dbd-9c3c1aea1a58.png)

**.env file**
`CANONICAL_URL=http://localhost:4000
ENABLE_SPA_ROUTING=true
EXTERNAL_GRAPHQL_URL=http://localhost:3030/graphql-alpha
INTERNAL_GRAPHQL_URL=http://localhost:3030/graphql-alpha
NODE_ENV=development
OAUTH2_ADMIN_PORT=4445
OAUTH2_AUTH_URL=http://localhost:4444/oauth2/auth
OAUTH2_CLIENT_ID=reaction-next-starterkit
OAUTH2_CLIENT_SECRET=CHANGEME
OAUTH2_HOST=hydra.auth.reaction.localhost
OAUTH2_IDP_HOST_URL=http://reaction.api.reaction.localhost:3000/
OAUTH2_REDIRECT_URL=http://localhost:4000/callback
OAUTH2_TOKEN_URL=http://hydra.auth.reaction.localhost:4444/oauth2/token
PORT=4000
SEGMENT_ANALYTICS_SKIP_MINIMIZE=true
SEGMENT_ANALYTICS_WRITE_KEY=ENTER_KEY_HERE
SESSION_MAX_AGE_MS=2592000000
SESSION_SECRET=CHANGEME
STRIPE_PUBLIC_API_KEY=ENTER_STRIPE_PUBLIC_KEY_HERE`

**Comment by ticean** [comment]
> I tried running on my local machine without docker

The project's `docker-compose.yml` [is configured to load env from the `.env` file](https://github.com/reactioncommerce/reaction-next-starterkit/blob/7c292aebdb82836df8efbd4a2c44c73476f7f13d/docker-compose.yml#L18-L19). If you choose to run without Compose then you'll need to take your own measures to ensure variables are correctly loaded into the environment.
