### ISSUE TITLE
Product grid item default image if none found

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#55]
## Issue

If an image is not available for a product grid item I get an infinite spinner or no image.

<img width="559" alt="screen shot 2018-04-23 at 3 13 22 pm" src="https://user-images.githubusercontent.com/42217/39156059-767c6f4a-4709-11e8-999b-443ffc116e5b.png">

## Solution

- We should have a default image in case one cannot be found.

**Comment by aldeed** [comment]
I am seeing placeholders, and this also now works when using devserver root for image URLs, on release-1.12.0 branch.
