### ISSUE TITLE
Add segment compatible analytics event tracking to the Product Grid

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#56]
We need to start tracking ecommerce analytics events in our starterkit. Initially we'll be tracking all of the Segment V2 Ecommerce Events. You can read the docs for that here: https://segment.com/docs/spec/ecommerce/v2/

Start by add documentation for the events tracked to our event tracking/analytics documentation, explaining the properties tracked and any mapping decisions that were made.

For our current implementation of the Product Grid, we'll need to track two events:

[Product List Viewed](https://segment.com/docs/spec/ecommerce/v2/#product-list-viewed)
[Product Clicked](https://segment.com/docs/spec/ecommerce/v2/#product-clicked)

**Comment by mikemurray** [comment]
@spencern The product price may be a range, should I take the `min` or `max` or `neither`?

**Comment by spencern** [comment]
I'd take the `min` if a range exists

**Comment by spencern** [comment]
maybe create a constant variable for this that we can permit customization of in the .env file later as well?
