### ISSUE TITLE
Product grid image size issue

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#65]
## Issue

Product grid items can have different sizes. The height of the medium and large grid items seems to be affected by the image. The height of images should all remain the same, but their widths should be different based on their weights.

### The highlighted image below shoun't be tall...

I should be the same height as the item next to it, but just as wide as it is now.

![reaction_shop](https://user-images.githubusercontent.com/42217/39318356-c586d528-4932-11e8-9584-bd86d5b8c864.png)

## Possible Solution

Images need to `object-fit` cover.

**Comment by kieckhafer** [comment]
@mikemurray what are your thoughts on the best way to go about this? Traditionally, I'd say set a fixed height (i.e. 325px), an then adjust that with media queries based on the width. Since we no longer have any stylesheets though, what's a good way to do this?
