### ISSUE TITLE
Product Grid Item does not display whole dollar price correctly

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#68]
When viewing a product grid item which has a price range - e.g. `$12.99 - $19.99` - the price is not rendered correctly. The "cents" side of the value should always be shown, even the price is a rounded amount. 

The currency symbol should also be shown on both sides of the range - e.g. `$12.99 - $19.99` _not_ `$12.99 - 19.99`

As you can see in this screen shot, the cents are not rendered for the low price, even though the price is not rounded and the currency symbol is only shown on the left-hand side of the range.
![image](https://user-images.githubusercontent.com/1203639/39368394-aebef752-49f6-11e8-88a8-69a005ca31d7.png)

This screenshot shows what it looks like in the Meteor UI
![image](https://user-images.githubusercontent.com/1203639/39368673-746cae2c-49f7-11e8-9ca5-f1b88a7e8a84.png)

This screenshot is from design showing the ideal @cassytaylor @rymorgan 
![image](https://user-images.githubusercontent.com/1203639/39368418-c038bdec-49f6-11e8-9a84-3681ba7c69e6.png)

**Comment by aldeed** [comment]
Made a separate ticket for one part of this in Reaction repo: https://github.com/reactioncommerce/reaction/issues/4221

**Comment by spencern** [comment]
Resolved by reactioncommerce/reaction#4222
