### ISSUE TITLE
Product grid item displays wrong image or spinner on load

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#69]
When I visit the product grid directly, or refresh the page while on the grid. Images are displayed incorrectly.

See this screen cap for an example.
<img src="http://g.recordit.co/hY1VyVpjfz.gif">

The correct images are:
Basic Reaction Product: Orange Square
My First Product: Vans shoe - Grey/Black
My Second Product: Vans Shoe - Red/Blue

As you can see, if I navigate around enough, the images eventually correctly display on the grid. After a refresh, the incorrect images are displayed again though.

**To Reproduce**
1. Start Reaction and dev-server in a container
2. Start the starterkit in a container
3. Add a product via reaction meteor operator with an image
4. Visit the grid via the starter kit
5. Add a second product via the meteor operator with a different image
6. Visit the grid again.
7. Click to visit the PDP for one of the products
8. Click the "Shop" tag to visit the grid

**Comment by willopez** [comment]
@spencern not able to reproduce, this is what I see: http://recordit.co/a0LWAU5iip
