### ISSUE TITLE
Product grid has no horizontal boundaries

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#71]
When viewing the product grid on a widescreen monitor, the product grid scales to the full width.

@rymorgan @cassytaylor what should the max width of the grid be? 

![image](https://user-images.githubusercontent.com/1203639/39371451-fa3b4840-49fe-11e8-96d9-98792d46998d.png)

**Comment by rymorgan** [comment]
Researching trends for an answer to this and how it should work responsively.

**Comment by rymorgan** [comment]
The short answer, for now, we should lock the grid at 1440 with padding on both sides.

**Further findings -** 

 -  The height of the images should be locked Almost no brands use   
   multiple width images on their standard grid only when they have special merchandised category or collections. 
 - The product image should be square it's up the brand to upload the right image only
   specialed brands use portrait or landscape
 - Images should fill grid w/ proper padding between them for the following scenarios - Desktop (4 wide), Tablet (3), Phone (1)
 - We can allow images to flex when the window shrinks before a breakpoints
 - In the future, we'd move filtering to a dropdown above the grid at vertical tablet size

**Comment by rymorgan** [comment]
Anyone interested in the competitive research around product grids here are my findings. (click on Product grid - size and flex tab.) https://docs.google.com/spreadsheets/d/1_whIDhSjW8RZ0N5VqpKwTMMuuR-KaT_FUSN6yIx5zTY/edit#gid=63930977

**Comment by nnnnat** [comment]
Resolved with PR #84
