### ISSUE TITLE
Create Breadcrumb Navigation component for use on Product Grid and PDP

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#78]
Create breadcrumb navigation component for use on the product grid and PDP pages (and potentially other pages)

The breadcrumb navigation should start with a `home` link which should link back to the index.

After that it should drill down into the tag category that the user is currently browsing, including the parents in the breadcrumb list if applicable.
e.g. if browsing the 'Skirts' tag within `Womens` and `Active Wear`, the breadcrumb list should render:
`Home > Womens > Active Wear > Skirts`

If on a PDP page, the breadcrumbs should show the breadcrumb list where the user originated followed by the product title

e.g.
`Home > Womens > Active Wear > Skirts > Patagonia Women's Lithia Skirt`

<img width="860" alt="image" src="https://user-images.githubusercontent.com/1203639/39504687-9b754ad8-4d8a-11e8-9c8b-49accebf1d86.png">

@rymorgan @cassytaylor If someone doesn't click in from a product grid to the PDP, what tag(s) should be shown in the breadcrumb list? The first tag probably?

**Comment by rymorgan** [comment]
@spencern I would think it would just home > product name.

**Comment by spencern** [comment]
@rymorgan that makes sense. Let's go with that.

**Comment by kieckhafer** [comment]
Was discussing with @rymorgan about what to do with displaying breadcrumbs in different situations.

We'd like some input, but what we are thinking is:

- If you navigate to a product from a tag page, the breadcrumbs display the lineage of tags taht got you there. So if you go to Tag A, or any sub-tag under Tag A's tag page, the crumbs will read `Home > Tag A > SubTag-A`. We think that's pretty straightforward.

However, when you go directly to a product from the default product grid, or say someone sends you a link and you go directly to a product, we were unsure what to do. Our thought is to show the Lowest level unique tag.

For example: 
- if a product is in `Home -> Tag A -> Tag A-1`, and nothing else, we'd show that.
- If a tag was in `Home -> Tag A -> Tag A-1` && `Home -> Tag A -> Tag A-2`, we'd show `Home -> Tag A`
- We don't know what to show if a tag is in `Home -> Tag A` && `Home -> Tag B`.

@spencern @aldeed thoughts on what we could show in the second example above? Thoughts on what we are thinking for the first example?

**Comment by spencern** [comment]
@kieckhafer I like this solution. Green light from me

**Comment by aldeed** [comment]
@kieckhafer Pending those discussions, I like the idea of just keeping it simple and showing the first hierarchy path that we find in the nav tree as the default behavior.

If they've clicked from a tag page, then it could definitely show that tag as the parent, but you'd have to track the ancestor tag(s) in mobx at the point of clicking in the nav if you want everything above that to be accurate. I'd say do that if it's easy but otherwise show only the parent and "Home" above that.

**Comment by aldeed** [comment]
@kieckhafer But maybe you can add that default logic in the CatalogProduct resolver on the server? Add a new `canonicalNavPath: [String]!` prop and a resolver for it, and have the resolver look up the first tag path it finds and return something like `["Womens", "Active Wear", "Skirts"]` (e.g., if product has "Skirts" tag) That way we can make that logic more customizable in the future but client UI won't need to change.

**Comment by kieckhafer** [comment]
@nnnnat I'm trying to tap into the existing `routingStore.tag` object.

When we land on a tag page, it sets the tag, however the tag is never unset, say if you go back to the main product grid, the tag you were just on is still set in `routingStore.tag`. I'm thinking about updating that so it unsets the tag if you aren't currently on a tag page, is there any reason you can think of why it wouldn't work? https://github.com/reactioncommerce/reaction-next-starterkit/blame/feat-78-kieckhafer-breadcrumbs/src/pages/tag.js#L44
