### ISSUE TITLE
Create image header component for product grid

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#79]
Create a component to display the featured image of a tag or category.

**Note:** currently we do not have an operator UI for adding an image to a tag.

- Add image url to tag schema
- Add image url to graphql query schema
- display image in grid as shown in designs if it exists
- Use `cover`

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/1203639/39505387-154e64da-4d8f-11e8-9016-5a83722b40e3.png">

**Comment by kieckhafer** [comment]
@spencern @rymorgan 

Is this header only going to be available on a tag page, or is it available on the default product grid as well?

And if available on the default grid, where should we store the image url in the schema?

**Comment by rymorgan** [comment]
Yes, the header will be only available to tagged pages. It should be fixed height that matches the height of product image containers and should be centered as it flexes responsively.

**Comment by spencern** [comment]
@kieckhafer 
Agreed with Ryan.
The thought is that the default product grid is unlikely to be used once we've got merchandise-able pages that can handle both products and content. If we need to, prior to that point, we could leverage a "convention based" tag for the index so that it can display a image.
