### ISSUE TITLE
Create items per page selector component

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#81]
Create an "items per page" select component to permit users to define the "limit" or max number of items to retrieve for a single page on the grid.

This setting should be persisted on the client such that when the user visits other tags, the limit is consistent.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/1203639/39506043-82421fd8-4d93-11e8-99a6-91d03d327dc6.png">

## Work
1. Create the component
1. Place the component above the grid.
1. When selection changes, update this in the URL with, e.g., `limit=20` in query string, and then refetch the data, staying on the current page (keeping the same `after` cursor).
1. Make sure this limit is respected by server side rendering, too.

**Comment by spencern** [comment]
@rymorgan what options should we have (20, 40, 50?) for the number of products to show?

**Comment by rymorgan** [comment]
The options should be 20, 60, 100.

If possible, in scenarios where the grid flexes to be 3 products wide(vertical tablet) instead of 4, it should change to numbers divisible by 3 so, 21, 60, and 102.

**Comment by rymorgan** [comment]
@cassytaylor will follow up with dropdown styles for the product count selector.

**Comment by cassytaylor** [comment]
Here's the style for the open dropdown button component - http://zpl.io/aRql70p

The default width of the button is based on the width of the default option, + 20px of padding on each side. In some cases, an option in the dropdown might exceed the length of the button; in that case, the button would expand when clicked to the width of the longest text string (+ padding). Here's an example - http://zpl.io/adMlGw5
