### ISSUE TITLE
Update Readme docs 

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#83]
Update the readme in this project to include clear documentation about the following:

Config and running inside docker
1. How this app should be configured 
2. Starting up the app initially
3. Starting the app a second time
4. Restarting the app after changing files. What types of files require removing and/or rebuilding the image
5. Teardown of the app and removing images

MobX
1. Quick ramp up guide for devs new to the starter kit
2. What type of data we're storing in each store
3. What considerations to make before adding data to an existing store or creating a new store

**Comment by kieckhafer** [comment]
I've started to add `mobx` documentation in PR #85 

This doesn't satisfy all the requirements for this ticket, so I didn't attach this ticket to the PR as others will add more docs to satisfy this.
