### ISSUE TITLE
Investigate and implement isomorphic logging

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-next-starterkit#93]
We currently have a logger implementation that I believe is only used for server logging. It would be nice to have a more isomorphic solution to keep logging consistent throughout the application.

**Comment by spencern** [comment]
Question from PR #75

**Comment by spencern** [comment]
From @jshimko 
- The Bunyan logger we use in Meteor right now has both a client and server version

@aldeed 
- You should not be "logging" something, you should be emitting events

@ticean 
- Event logs should have a somewhat normalized schema
- Be aware of the different schemas associated with different types of logs/events
- We should define standard schemas for logs

**Comment by spencern** [comment]
@ticean @aldeed @nnnnat I think we need to refine this issue before it can be worked on. I'm going to leave it open for discussion for now, but it's not ready to be worked on or scheduled at this point.

**Comment by spencern** [comment]
Agree. Closing this issue for now.
