### ISSUE TITLE
Connect Add To Cart Button to GraphQL mutation

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-next-starterkit#95]
The PDP page `Add To Cart` button (https://github.com/reactioncommerce/reaction-next-starterkit/pull/94) is currently just a UI placeholder. We need to connect the button to our GraphQL endpoint  (which currently doesn't exist) and pass the data as needed.

Additionally we'll need to trigger showing the mini-cart after an item has been successfully added to the cart.

This ticket needs to deal with the logic around deciding whether to call createCart or addCartItems.

**Comment by aldeed** [comment]
This should be unblocked if you work against this branch until it's merged: https://github.com/reactioncommerce/reaction/pull/4412

See the comments in that PR for example mutations and variables
